package main

import (
	"fmt"
	"log"
	"math/rand/v2"
	"net"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

func serviceActive(svc string) bool {
	return exec.Command("systemctl", "is-active", "--quiet", svc).Run() == nil
}

func unitExists(svc string) bool {
	for _, d := range []string{"/etc/systemd/system/", "/lib/systemd/system/", "/usr/lib/systemd/system/"} {
		if _, err := os.Stat(d + svc + ".service"); err == nil {
			return true
		}
	}
	return false
}

// hyOpts are the choices for a new Hysteria config.
type hyOpts struct {
	Port   string // "443" or a hopping range "20000-50000"
	Obfs   string // salamander, gecko, ""
	Domain string // Let's Encrypt via Hysteria's ACME; "" = self-signed
	Email  string
}

const hopRange = "20000-50000"

// askHyOpts asks for the Hysteria settings; a flag given on the command line
// (port != "") skips its question.
func askHyOpts(p *prompter, port, host string) hyOpts {
	o := hyOpts{Port: port, Obfs: "salamander"}
	if o.Port == "" {
		switch p.choose("Порт Hysteria (UDP):", []string{
			"443 — выглядит как обычный HTTPS/QUIC",
			"случайный",
			"свой",
			"диапазон " + hopRange + " — port hopping, сложнее заблокировать (Hysteria ≥ 2.8)",
		}, 0) {
		case 0:
			o.Port = "443"
		case 1:
			o.Port = strconv.Itoa(20000 + rand.IntN(40000))
		case 2:
			o.Port = p.port("Порт: ")
		case 3:
			o.Port = hopRange
			if !hysteriaAtLeast(2, 8) {
				fmt.Println("  ✗ установленная Hysteria старше 2.8 и не умеет слушать диапазон — беру 443")
				o.Port = "443"
			}
		}
	}
	o.Obfs = []string{"salamander", "gecko", ""}[p.choose("Обфускация:", []string{
		"salamander — трафик не похож ни на что, рекомендую для РФ",
		"gecko — salamander + дробление рукопожатия (экспериментальная, Hysteria ≥ 2.9.2, mihomo тоже нужен свежий)",
		"без обфускации — выглядит как HTTP/3-сайт (маскировка под bing.com)",
	}, 0)]
	if p.choose("Сертификат:", []string{
		"self-signed — домен не нужен, клиенты проверяют сертификат по отпечатку",
		"свой домен через Let's Encrypt — домен должен указывать на этот сервер, TCP 80/443 свободны",
	}, 0) == 1 {
		for o.Domain == "" {
			o.Domain = strings.ToLower(p.line("Домен: ", ""))
		}
		o.Email = p.line("E-mail для Let's Encrypt (Enter — без него): ", "")
		if !resolvesTo(o.Domain, host) && !p.yes(fmt.Sprintf("  %s не указывает на %s. Всё равно продолжить?", o.Domain, host), false) {
			log.Fatal("✗ сначала направь A-запись домена на сервер")
		}
	}
	return o
}

func resolvesTo(domain, ip string) bool {
	ips, _ := net.LookupHost(domain)
	for _, a := range ips {
		if a == ip {
			return true
		}
	}
	return false
}

var versionRe = regexp.MustCompile(`v(\d+)\.(\d+)`)

func hysteriaAtLeast(major, minor int) bool {
	out, _ := exec.Command("/usr/local/bin/hysteria", "version").Output()
	m := versionRe.FindStringSubmatch(string(out))
	if m == nil {
		return false
	}
	a, _ := strconv.Atoi(m[1])
	b, _ := strconv.Atoi(m[2])
	return a > major || a == major && b >= minor
}

// freshSetup writes a working config for an official Hysteria install whose
// config never ran (the get.hy2.sh template with a placeholder ACME domain).
// Hysteria itself (binary, user, unit) comes from the official installer.
func freshSetup(cfgPath, svc string, o hyOpts) {
	if _, err := os.Stat("/usr/local/bin/hysteria"); err != nil || !unitExists(svc) {
		log.Fatalf("✗ Hysteria не установлена. Сначала официальный установщик:\n    bash <(curl -fsSL https://get.hy2.sh/)\n  затем снова hy-panel install")
	}
	uid, gid := 0, 0
	if u, err := user.Lookup("hysteria"); err == nil {
		uid, _ = strconv.Atoi(u.Uid)
		gid, _ = strconv.Atoi(u.Gid)
	}
	dir := filepath.Dir(cfgPath)
	step("directory "+dir, os.MkdirAll(dir, 0o750))

	var tlsBlock, files string
	files = cfgPath
	if o.Domain == "" {
		crt, key := filepath.Join(dir, "server.crt"), filepath.Join(dir, "server.key")
		os.Remove(crt)
		os.Remove(key)
		// The name only has to match the SNI (sniGuard); clients pin the cert.
		step("self-signed certificate", newSelfSigned(crt, key, "bing.com"))
		tlsBlock = fmt.Sprintf("tls:\n  cert: %s\n  key: %s\n", crt, key)
		files += " " + crt + " " + key
	} else {
		tlsBlock = fmt.Sprintf("acme:\n  domains:\n    - %s\n", o.Domain)
		if o.Email != "" {
			tlsBlock += fmt.Sprintf("  email: %s\n", o.Email)
		}
	}
	var obfsBlock string
	switch o.Obfs {
	case "salamander", "gecko":
		obfsBlock = fmt.Sprintf("obfs:\n  type: %[1]s\n  %[1]s:\n    password: %[2]s\n", o.Obfs, randStr(24))
	default:
		// Without obfs Hysteria answers browsers like a normal HTTP/3 site.
		obfsBlock = "masquerade:\n  type: proxy\n  proxy:\n    url: https://www.bing.com/\n    rewriteHost: true\n"
	}

	if b, err := os.ReadFile(cfgPath); err == nil {
		if _, err := os.Stat(cfgPath + backupExt); os.IsNotExist(err) {
			step("backup of the old config → "+cfgPath+backupExt, os.WriteFile(cfgPath+backupExt, b, 0o600))
		}
	}
	conf := fmt.Sprintf("# generated by hy-panel install\nlisten: :%s\n\n%s\n%s\nauth:\n  type: http\n  http:\n    url: http://%s/auth\n\ntrafficStats:\n  listen: %s\n  secret: %s\n",
		o.Port, tlsBlock, obfsBlock, panelAddr, statsAddr, randStr(32))
	step("hysteria config "+cfgPath, os.WriteFile(cfgPath, []byte(conf), 0o640))

	// Directory owned by hysteria (ACME writes its state there), files readable by its group.
	os.Chown(dir, uid, gid)
	for _, f := range strings.Fields(files) {
		os.Chown(f, 0, gid)
		os.Chmod(f, 0o640)
	}
	step("enable "+svc, systemctl("enable", svc))

	if out, err := exec.Command("ufw", "status").Output(); err == nil && strings.Contains(string(out), "Status: active") {
		rules := []string{strings.Replace(o.Port, "-", ":", 1) + "/udp"}
		if o.Domain != "" {
			rules = append(rules, "80/tcp", "443/tcp") // ACME challenges
		}
		for _, r := range rules {
			step("ufw allow "+r, exec.Command("ufw", "allow", r).Run())
		}
	}
}
