package main

import (
	"crypto/tls"
	"fmt"
	"log"
	"math/rand/v2"
	"net"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"regexp"
	"slices"
	"strconv"
	"strings"
)

// generatedMark heads a Hysteria config written by freshSetup.
const generatedMark = "# generated by hy-panel install"

// needsFreshConfig reports whether the Hysteria config has yet to be set up:
// it is missing or still the official installer's template. Any other config,
// including one this installer wrote, is adopted as is, even when Hysteria is
// stopped, so re-running install never changes the client links.
func needsFreshConfig(cfgPath string) bool {
	b, err := os.ReadFile(cfgPath)
	return err != nil || isTemplate(b)
}

// isTemplate: get.hy2.sh writes an ACME config for this placeholder domain.
func isTemplate(conf []byte) bool { return strings.Contains(string(conf), "your.domain.net") }

func keyPairOK(crt, key string) bool {
	_, err := tls.LoadX509KeyPair(crt, key)
	return err == nil
}

func serviceActive(svc string) bool {
	return systemctl("is-active", "--quiet", svc) == nil
}

func unitExists(svc string) bool {
	for _, d := range []string{"/etc/systemd/system/", "/lib/systemd/system/", "/usr/lib/systemd/system/"} {
		if _, err := os.Stat(d + svc + ".service"); err == nil {
			return true
		}
	}
	return false
}

// hyOpts are the choices for a new Hysteria config.
type hyOpts struct {
	Port   string // "443" or a hopping range "20000-50000"
	Obfs   string // salamander, gecko, ""
	Domain string // Let's Encrypt via Hysteria's ACME; "" = self-signed
	Email  string
}

const hopRange = "20000-50000"

// askHyOpts asks for the Hysteria settings; a flag given on the command line
// (port != "") skips its question.
func askHyOpts(p *prompter, port, host string) hyOpts {
	hv := hysteriaVersion()
	o := hyOpts{Port: port, Obfs: "salamander"}
	if o.Port == "" {
		switch p.choose("Порт Hysteria (UDP):", []string{
			"443 — выглядит как обычный HTTPS/QUIC",
			"случайный",
			"свой",
			"диапазон " + hopRange + " — port hopping, сложнее заблокировать (Hysteria ≥ 2.8)",
		}, 0) {
		case 0:
			o.Port = "443"
		case 1:
			o.Port = strconv.Itoa(20000 + rand.IntN(40000))
		case 2:
			o.Port = p.port("Порт: ")
		case 3:
			o.Port = hv.or(hyVersion{2, 8, 0}, hopRange, "443", "диапазон портов")
		}
	}
	o.Obfs = []string{"salamander", "gecko", ""}[p.choose("Обфускация:", []string{
		"salamander — трафик не похож ни на что, рекомендую для РФ",
		"gecko — salamander + дробление рукопожатия (экспериментальная, Hysteria ≥ 2.9.2, mihomo тоже нужен свежий)",
		"без обфускации — выглядит как HTTP/3-сайт (маскировка под bing.com)",
	}, 0)]
	if o.Obfs == "gecko" {
		o.Obfs = hv.or(hyVersion{2, 9, 2}, "gecko", "salamander", "gecko")
	}
	if p.choose("Сертификат:", []string{
		"self-signed — домен не нужен, клиенты проверяют сертификат по отпечатку",
		"свой домен через Let's Encrypt — домен должен указывать на этот сервер, TCP 80/443 свободны",
	}, 0) == 1 {
		o.Domain = strings.ToLower(p.need("Домен: "))
		o.Email = p.line("E-mail для Let's Encrypt (Enter — без него): ", "")
		if !resolvesTo(o.Domain, host) && !p.yes(fmt.Sprintf("  %s не указывает на %s. Всё равно продолжить?", o.Domain, host), false) {
			log.Fatal("✗ сначала направь A-запись домена на сервер")
		}
	}
	return o
}

// resolvesTo reports whether domain resolves to host (an IP, or a domain whose
// addresses are compared).
func resolvesTo(domain, host string) bool {
	if strings.EqualFold(domain, host) {
		return true
	}
	want, _ := net.LookupHost(host) // an IP comes back as is
	ips, _ := net.LookupHost(domain)
	return slices.ContainsFunc(ips, func(a string) bool { return slices.Contains(want, a) })
}

const hysteriaBin = "/usr/local/bin/hysteria"

// requireHysteria stops the install when the official Hysteria is missing.
func requireHysteria(svc string) {
	if _, err := os.Stat(hysteriaBin); err != nil || !unitExists(svc) {
		log.Fatalf("✗ Hysteria не установлена. Сначала официальный установщик:\n    bash <(curl -fsSL https://get.hy2.sh/)\n  затем снова hy-panel install")
	}
}

// hyVersion is major.minor.patch of the installed Hysteria; zero if unknown.
type hyVersion [3]int

var versionRe = regexp.MustCompile(`v(\d+)\.(\d+)\.(\d+)`)

func hysteriaVersion() hyVersion {
	out, _ := exec.Command(hysteriaBin, "version").Output()
	var v hyVersion
	if m := versionRe.FindStringSubmatch(string(out)); m != nil {
		for i := range v {
			v[i], _ = strconv.Atoi(m[i+1])
		}
	}
	return v
}

// or returns want when the installed version is at least min, else tells the
// user that feature is unavailable and returns fallback.
func (v hyVersion) or(min hyVersion, want, fallback, feature string) string {
	if slices.Compare(v[:], min[:]) >= 0 {
		return want
	}
	fmt.Printf("  ✗ %s нужна Hysteria ≥ %d.%d.%d, установлена %d.%d.%d — беру %s\n", feature, min[0], min[1], min[2], v[0], v[1], v[2], fallback)
	return fallback
}

// freshSetup writes a working config for an official Hysteria install that is
// not configured yet (no config, or the get.hy2.sh template), or on -fresh.
// Hysteria itself (binary, user, unit) comes from the official installer.
func freshSetup(cfgPath, svc string, o hyOpts) {
	uid, gid := 0, 0
	if u, err := user.Lookup("hysteria"); err == nil {
		uid, _ = strconv.Atoi(u.Uid)
		gid, _ = strconv.Atoi(u.Gid)
	}
	dir := filepath.Dir(cfgPath)
	step("directory "+dir, os.MkdirAll(dir, 0o750))

	var tlsBlock string
	files := []string{cfgPath}
	if o.Domain == "" {
		crt, key := filepath.Join(dir, "server.crt"), filepath.Join(dir, "server.key")
		// Keep an existing self-signed certificate: clients pin it, a new one
		// breaks their links. Anything else (e.g. a CA-issued cert left there)
		// would not be pinned, so it is replaced.
		if ci, err := readCert(crt); err != nil || !ci.SelfSigned || !keyPairOK(crt, key) {
			// The name only has to match the SNI (sniGuard); clients pin the cert.
			step("self-signed certificate", newSelfSigned(crt, key, "bing.com"))
		}
		tlsBlock = fmt.Sprintf("tls:\n  cert: %s\n  key: %s\n", crt, key)
		files = append(files, crt, key)
	} else {
		// Explicit dir: by default ACME state goes to the unit's working directory.
		acmeDir := filepath.Join(dir, "acme")
		step("directory "+acmeDir, os.MkdirAll(acmeDir, 0o700))
		os.Chown(acmeDir, uid, gid) // the only place hysteria may write
		tlsBlock = fmt.Sprintf("acme:\n  domains:\n    - %s\n  dir: %s\n", o.Domain, acmeDir)
		if o.Email != "" {
			tlsBlock += fmt.Sprintf("  email: %s\n", o.Email)
		}
	}
	var obfsBlock string
	switch o.Obfs {
	case "salamander", "gecko":
		// Keep the current obfs password, like the certificate: it is in every link.
		pass := randStr(24)
		if old, err := loadHyConfig(cfgPath); err == nil {
			if _, p := old.obfs(); p != "" {
				pass = p
			}
		}
		obfsBlock = fmt.Sprintf("obfs:\n  type: %[1]s\n  %[1]s:\n    password: %[2]s\n", o.Obfs, pass)
	default:
		// Without obfs Hysteria answers browsers like a normal HTTP/3 site.
		obfsBlock = "masquerade:\n  type: proxy\n  proxy:\n    url: https://www.bing.com/\n    rewriteHost: true\n"
	}

	if b, err := os.ReadFile(cfgPath); err == nil {
		step("backup of the old config → "+cfgPath+backupExt, backupOnce(cfgPath, b))
	}
	conf := fmt.Sprintf(generatedMark+"\nlisten: :%s\n\n%s\n%s\nauth:\n  type: http\n  http:\n    url: %s\n\ntrafficStats:\n  listen: %s\n  secret: %s\n",
		o.Port, tlsBlock, obfsBlock, authURL, statsAddr, randStr(32))
	step("hysteria config "+cfgPath, os.WriteFile(cfgPath, []byte(conf), 0o640))

	// Directory and files root-owned, readable by hysteria's group.
	os.Chown(dir, 0, gid)
	for _, f := range files {
		os.Chown(f, 0, gid)
		os.Chmod(f, 0o640)
	}
	step("enable "+svc, systemctl("enable", svc))

	rules := []string{strings.Replace(o.Port, "-", ":", 1) + "/udp"}
	if o.Domain != "" {
		rules = append(rules, "80/tcp", "443/tcp") // ACME challenges
	}
	ufwAllow(rules...)
}
