package main

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"strconv"
	"strings"
)

func serviceActive(svc string) bool {
	return exec.Command("systemctl", "is-active", "--quiet", svc).Run() == nil
}

func unitExists(svc string) bool {
	for _, d := range []string{"/etc/systemd/system/", "/lib/systemd/system/", "/usr/lib/systemd/system/"} {
		if _, err := os.Stat(d + svc + ".service"); err == nil {
			return true
		}
	}
	return false
}

// freshSetup writes a working config for an official Hysteria install whose
// config never ran (the get.hy2.sh template with a placeholder ACME domain).
// Hysteria itself (binary, user, unit) comes from the official installer.
func freshSetup(cfgPath, svc, port string) {
	if _, err := os.Stat("/usr/local/bin/hysteria"); err != nil || !unitExists(svc) {
		log.Fatalf("✗ Hysteria не установлена. Сначала официальный установщик:\n    bash <(curl -fsSL https://get.hy2.sh/)\n  затем снова hy-panel install")
	}
	gid := 0
	if g, err := user.LookupGroup("hysteria"); err == nil {
		gid, _ = strconv.Atoi(g.Gid)
	}
	dir := filepath.Dir(cfgPath)
	step("directory "+dir, os.MkdirAll(dir, 0o750))
	crt, key := filepath.Join(dir, "server.crt"), filepath.Join(dir, "server.key")
	os.Remove(crt)
	os.Remove(key)
	// SNI-only name: clients pin the cert, the name just has to match (sniGuard).
	step("self-signed certificate", newSelfSigned(crt, key, "bing.com"))

	if b, err := os.ReadFile(cfgPath); err == nil {
		if _, err := os.Stat(cfgPath + backupExt); os.IsNotExist(err) {
			step("backup of the old config → "+cfgPath+backupExt, os.WriteFile(cfgPath+backupExt, b, 0o600))
		}
	}
	conf := fmt.Sprintf(`# generated by hy-panel install
listen: :%s

tls:
  cert: %s
  key: %s

obfs:
  type: salamander
  salamander:
    password: %s

auth:
  type: http
  http:
    url: http://%s/auth

trafficStats:
  listen: %s
  secret: %s
`, port, crt, key, randStr(24), panelAddr, statsAddr, randStr(32))
	step("hysteria config "+cfgPath, os.WriteFile(cfgPath, []byte(conf), 0o640))
	for _, p := range []string{dir, cfgPath, crt, key} {
		os.Chown(p, 0, gid)
	}
	os.Chmod(key, 0o640)
	step("enable "+svc, systemctl("enable", svc))
	if out, err := exec.Command("ufw", "status").Output(); err == nil && strings.Contains(string(out), "Status: active") {
		step("ufw allow "+port+"/udp", exec.Command("ufw", "allow", port+"/udp").Run())
	}
}
